Repository ReAGEnT-WiSe2021-22/frontend-v2, pull requests merged in 2021-12, with the labels that each got.

#14 Party reputation/ft/types
  packages/container/package.json
  packages/container/src/index.tsx
  packages/container/src/setup.ts
  packages/container/src/types.ts
  packages/party-reputation/package.json
  packages/party-reputation/src/direflow-components/party-reputation/App.tsx
  packages/party-reputation/src/direflow-components/party-reputation/components/mock-client.tsx
  packages/party-reputation/src/direflow-components/party-reputation/index.tsx
  packages/party-reputation/src/hooks/useEnvironment.tsx
  packages/party-reputation/src/index.tsx
  packages/party-reputation/src/types.ts
  packages/party-reputation/src/utils/fixture.ts
  packages/party-reputation/src/utils/mock-server.ts
  yarn.lock
Labels: feature

#13 chore(dependency): upgrade react and react-dom version
  packages/search-engine/.eslintrc.js
  packages/search-engine/package.json
  packages/search-engine/src/direflow-components/search-engine/App.tsx
Labels: dependencies

#12 fix(router): use React router Link instead of anchor tag
  packages/container/package.json
  packages/container/src/import-wc.ts
  packages/container/src/index.tsx
  packages/container/src/layout.tsx
  yarn.lock
Labels: bug
